// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace De.Dhoffmann.Mono.Adfcnewsapp.Touch
{
	public partial class NewsDetailViewController : UIViewController
	{
		public NewsDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
