// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace De.Dhoffmann.Mono.Adfcnewsapp.Touch
{
	public partial class WebViewController : UIViewController
	{
		public WebViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
