// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace de.dhoffmann.mono.adfcnewsapp.droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo_adfc = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int cbDateIndicate = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int imageView1 = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int llHeader = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int lvDataSubscription = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int menu = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int menuGetDataNow = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int menuSettings = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dates = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int News = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Tabs = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int Headline = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int MailLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MainTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int TabContent = 2131034114;
			
			private Style()
			{
			}
		}
	}
}
