// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace de.dhoffmann.mono.adfcnewsapp.droid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Share = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int btnNextNewsEntry = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int btnShare = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btnWebsite = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int cbDataUpdate = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int cbDateIndicate = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int cbFeedItem = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout1 = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int llHeader = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int lvDataSubscription = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int lvNews = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int menu = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int menuGetDataNow = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int menuMarkAllRead = 2131099674;
			
			// aapt resource value: 0x7f06000d
			public const int menuMarkAsUnread = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int menuSettings = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int menuShowReadNews = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int progressLoading = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int scrollView1 = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int tvDate = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int tvName = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int tvNewsDetail = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int tvNewsDetailDate = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tvNewsDetailFeedTitle = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int tvNewsItemHeadline = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int wvNewsDetail = 2131099659;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dates = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int News = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NewsDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewsDetailsMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewsListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Settings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SettingsFeedListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Tabs = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TabsMenu = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int Headline = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int MailLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MainTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int TabContent = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Theme_Splash = 2131034116;
			
			private Style()
			{
			}
		}
	}
}
